# Generated by Django 5.1.6 on 2025-02-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_1', '0003_business_delete_apikey_delete_client_delete_userfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=1000)),
                ('client_number', models.CharField(max_length=20)),
                ('bussiness_name', models.CharField(max_length=30)),
                ('is_client', models.BooleanField()),
                ('time_of_chat', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
