# Generated by Django 5.1.6 on 2025-02-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_1', '0004_chats_delete_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussniess_name', models.CharField(max_length=30)),
                ('api_key', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=50)),
                ('llm_model', models.CharField(max_length=50)),
            ],
        ),
    ]
