# Generated by Django 5.1.6 on 2025-02-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_1', '0005_bussiness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bussiness',
            old_name='bussniess_name',
            new_name='bussiness_name',
        ),
    ]
