# Generated by Django 5.1.6 on 2025-02-17 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_1', '0007_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bussiness_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_1.bussiness'),
        ),
    ]
