# Generated by Django 5.1.6 on 2025-02-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_1', '0008_alter_client_bussiness_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bussiness_name',
            field=models.CharField(max_length=30),
        ),
    ]
