# Generated by Django 5.1.6 on 2025-02-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_1', '0011_alter_chats_bussiness_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_email',
            field=models.CharField(default='no@emal.com', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='client_name',
            field=models.CharField(default='noname', max_length=30),
        ),
    ]
