# Generated by Django 5.1.6 on 2025-02-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=1000)),
                ('user_id', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
    ]
